import { PublicProperty } from './types';

export const VERIFIED_MUMBAI_FALLBACKS: (PublicProperty & {
  metroDistance?: string;
  aiWhyRecommended?: string;
  aiMatchScore?: number;
  isZeroDeposit?: boolean;
})[] = [
  {
    id: 'prop-mumbai-01',
    title: 'Spacious 2 BHK Sea-Facing High Rise Apartment',
    category: 'residential',
    type: 'flat',
    description: 'Direct owner flat on 18th floor with uninterrupted Arabian Sea views, Italian marble flooring, and modular European kitchen.',
    price: 75000,
    deposit: 150000,
    maintenance: 4500,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Bandra West',
    address: 'Carter Road, Bandra West, Mumbai',
    latitude: 19.0607,
    longitude: 72.8258,
    bedrooms: '2',
    bathrooms: 2,
    area: 980,
    furnishing: 'fully_furnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'power_backup', 'gym', 'pool', 'security', 'balcony', 'pet_friendly'],
    tenant_preferences: ['family', 'bachelors', 'working_professionals'],
    views_count: 840,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '350m to Bandra Metro',
    aiWhyRecommended: 'Direct Owner • Sea Facing • High Natural Light',
    aiMatchScore: 99,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-1-1',
        image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-1-2',
        image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
      {
        id: 'img-1-3',
        image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 3,
      },
    ],
  },
  {
    id: 'prop-mumbai-02',
    title: 'Luxury 3 BHK Gated Society Flat with Lake View',
    category: 'residential',
    type: 'flat',
    description: 'Premium Hiranandani complex flat with panoramic Powai lake view, clubhouse membership, central AC and 2 covered car parkings.',
    price: 68000,
    deposit: 136000,
    maintenance: 5000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Powai',
    address: 'Hiranandani Gardens, Powai, Mumbai',
    latitude: 19.1176,
    longitude: 72.9060,
    bedrooms: '3',
    bathrooms: 3,
    area: 1420,
    furnishing: 'semi_furnished',
    parking: '2 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'power_backup', 'gym', 'pool', 'security', 'balcony'],
    tenant_preferences: ['family', 'working_professionals'],
    views_count: 620,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '500m to Powai Metro',
    aiWhyRecommended: 'Gated Luxury Society • Lake View • 2 Parking',
    aiMatchScore: 98,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-2-1',
        image_url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-2-2',
        image_url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
      {
        id: 'img-2-3',
        image_url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 3,
      },
    ],
  },
  {
    id: 'prop-mumbai-03',
    title: 'Modern 1 BHK Studio Apartment with Zero Deposit',
    category: 'residential',
    type: 'studio',
    description: 'Fully furnished studio apartment equipped with Smart TV, high-speed Wi-Fi, work desk, and microwave. Ideal for BKC corporate professionals.',
    price: 38000,
    deposit: 0,
    maintenance: 2500,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'BKC',
    address: 'Bandra Kurla Complex, Mumbai',
    latitude: 19.0657,
    longitude: 72.8687,
    bedrooms: '1',
    bathrooms: 1,
    area: 540,
    furnishing: 'fully_furnished',
    parking: '1 Open',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'power_backup', 'security'],
    tenant_preferences: ['bachelors', 'working_professionals', 'any'],
    views_count: 980,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '200m to BKC Metro',
    aiWhyRecommended: 'Zero Deposit Pass • Walk to BKC Offices • WFH Setup',
    aiMatchScore: 97,
    isZeroDeposit: true,
    property_images: [
      {
        id: 'img-3-1',
        image_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-3-2',
        image_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-04',
    title: 'Cozy 1 RK / Studio Flat in Prime Andheri West',
    category: 'residential',
    type: 'room',
    description: 'Direct owner studio flat with separate kitchenette, washing machine, refrigerator, and AC. Just 5 mins walk to metro & Lokhandwala market.',
    price: 24000,
    deposit: 48000,
    maintenance: 1500,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Andheri West',
    address: 'Lokhandwala Complex, Andheri West, Mumbai',
    latitude: 19.1363,
    longitude: 72.8277,
    bedrooms: '1',
    bathrooms: 1,
    area: 380,
    furnishing: 'fully_furnished',
    parking: 'None',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'power_backup', 'security'],
    tenant_preferences: ['bachelors', 'working_professionals', 'any'],
    views_count: 450,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '400m to DN Nagar Metro',
    aiWhyRecommended: 'Budget Friendly • Near Lokhandwala • Furnished',
    aiMatchScore: 96,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-4-1',
        image_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-4-2',
        image_url: 'https://images.unsplash.com/photo-1502005229762-ee152da915d6?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-05',
    title: 'Ultra-Luxury 3 BHK Penthouse with Private Terrace',
    category: 'residential',
    type: 'flat',
    description: 'Designer duplex penthouse with sprawling private wooden deck terrace, skyline views of Bandra-Worli Sea Link, private elevator access and valet parking.',
    price: 145000,
    deposit: 290000,
    maintenance: 8000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Worli & Lower Parel',
    address: 'Worli Seaface, Mumbai',
    latitude: 19.0144,
    longitude: 72.8155,
    bedrooms: '3',
    bathrooms: 4,
    area: 2100,
    furnishing: 'fully_furnished',
    parking: '2 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'power_backup', 'gym', 'pool', 'security', 'balcony', 'pet_friendly'],
    tenant_preferences: ['family', 'working_professionals'],
    views_count: 1120,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '600m to Worli Metro',
    aiWhyRecommended: 'Private Terrace • Sea Link View • High Ceilings',
    aiMatchScore: 99,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-5-1',
        image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-5-2',
        image_url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
      {
        id: 'img-5-3',
        image_url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 3,
      },
    ],
  },
  {
    id: 'prop-mumbai-06',
    title: 'Peaceful 2 BHK Flat near Juhu Beach with Balcony',
    category: 'residential',
    type: 'flat',
    description: 'Quiet green residential lane flat in Juhu Scheme. Walking distance to the beach, high natural cross-ventilation, and 24x7 water supply.',
    price: 85000,
    deposit: 170000,
    maintenance: 4000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Juhu',
    address: 'JVPD Scheme, Juhu, Mumbai',
    latitude: 19.1075,
    longitude: 72.8263,
    bedrooms: '2',
    bathrooms: 2,
    area: 1050,
    furnishing: 'semi_furnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'security', 'balcony'],
    tenant_preferences: ['family', 'bachelors', 'any'],
    views_count: 530,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '800m to Metro',
    aiWhyRecommended: 'Walking to Juhu Beach • Green Society • Gated',
    aiMatchScore: 95,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-6-1',
        image_url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-6-2',
        image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-07',
    title: 'Modern 2 BHK Gated Flat in Lower Parel High-Rise',
    category: 'residential',
    type: 'flat',
    description: 'High-rise tower apartment opposite Palladium Mall. Access to swimming pool, squash court, rooftop sky lounge and biometric access.',
    price: 62000,
    deposit: 124000,
    maintenance: 3800,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Worli & Lower Parel',
    address: 'Senapati Bapat Marg, Lower Parel, Mumbai',
    latitude: 18.9953,
    longitude: 72.8285,
    bedrooms: '2',
    bathrooms: 2,
    area: 920,
    furnishing: 'fully_furnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'power_backup', 'gym', 'pool', 'security', 'balcony'],
    tenant_preferences: ['working_professionals', 'family'],
    views_count: 760,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '300m to Lower Parel Monorail',
    aiWhyRecommended: 'Opposite Palladium • High Floor • Gym & Pool',
    aiMatchScore: 98,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-7-1',
        image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-7-2',
        image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-08',
    title: 'Sunlit 2 BHK Flat with Balcony in Bandra West',
    category: 'residential',
    type: 'flat',
    description: 'Charming sun-drenched home off Hill Road. Brand new inverter, piped gas, designer lighting fixtures, and peaceful society environment.',
    price: 55000,
    deposit: 110000,
    maintenance: 3000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Bandra West',
    address: 'Hill Road, Bandra West, Mumbai',
    latitude: 19.0558,
    longitude: 72.8315,
    bedrooms: '2',
    bathrooms: 2,
    area: 880,
    furnishing: 'fully_furnished',
    parking: '1 Open',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'security', 'balcony', 'pet_friendly'],
    tenant_preferences: ['family', 'bachelors', 'any'],
    views_count: 890,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '450m to Bandra Metro',
    aiWhyRecommended: 'Off Hill Road • Pet Friendly • Low Maintenance',
    aiMatchScore: 97,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-8-1',
        image_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-8-2',
        image_url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-09',
    title: 'Furnished Executive Commercial Office Space in BKC',
    category: 'commercial',
    type: 'office',
    description: 'Plug-and-play Grade A commercial workspace with 18 workstations, 2 MD cabins, 1 conference room, cafeteria, and 100% DG power backup.',
    price: 95000,
    deposit: 190000,
    maintenance: 8500,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'BKC',
    address: 'G Block, BKC, Mumbai',
    latitude: 19.0664,
    longitude: 72.8682,
    bedrooms: null,
    bathrooms: 2,
    area: 1200,
    furnishing: 'fully_furnished',
    parking: '2 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'parking', 'power_backup', 'security'],
    tenant_preferences: ['working_professionals'],
    views_count: 670,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '150m to BKC Metro',
    aiWhyRecommended: 'Grade A Office • 18 Workstations • Plug & Play',
    aiMatchScore: 98,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-9-1',
        image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-9-2',
        image_url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-10',
    title: 'Private AC Room in 3 BHK Flat for Flatmate',
    category: 'residential',
    type: 'room',
    description: 'Spacious master bedroom with private attached washroom in a fully furnished 3 BHK. Housekeeping, Wi-Fi, and Cook setup already in place.',
    price: 18500,
    deposit: 25000,
    maintenance: 1200,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Andheri West',
    address: 'Veera Desai Road, Andheri West, Mumbai',
    latitude: 19.1311,
    longitude: 72.8361,
    bedrooms: '1',
    bathrooms: 1,
    area: 250,
    furnishing: 'fully_furnished',
    parking: '1 Open',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'power_backup', 'security', 'pet_friendly'],
    tenant_preferences: ['bachelors', 'working_professionals'],
    views_count: 510,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '300m to Azad Nagar Metro',
    aiWhyRecommended: 'Attached Bath • Cook & Maid Setup • VibeMatched',
    aiMatchScore: 96,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-10-1',
        image_url: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-10-2',
        image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4b13?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-11',
    title: 'Budget-Friendly 1 BHK Flat in Gated Complex',
    category: 'residential',
    type: 'flat',
    description: 'Peaceful society with 24x7 security, children park, supermarket inside society, and quick auto connectivity to railway station.',
    price: 22000,
    deposit: 44000,
    maintenance: 1800,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Thane West',
    address: 'Ghodbunder Road, Thane West, Mumbai',
    latitude: 19.2458,
    longitude: 72.9734,
    bedrooms: '1',
    bathrooms: 1,
    area: 550,
    furnishing: 'semi_furnished',
    parking: '1 Open',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['lift', 'security', 'power_backup', 'parking'],
    tenant_preferences: ['family', 'bachelors', 'any'],
    views_count: 320,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '500m to Metro',
    aiWhyRecommended: 'Budget Friendly • Gated Society • Clean Air',
    aiMatchScore: 94,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-11-1',
        image_url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-11-2',
        image_url: 'https://images.unsplash.com/photo-1502005229762-ee152da915d6?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-mumbai-12',
    title: 'Prime Retail Corner Shop on High Footfall Commercial Street',
    category: 'commercial',
    type: 'shop',
    description: 'Glass fronted ground floor retail space on Linking Road. Excellent branding visibility, 3-phase electricity, and dedicated customer parking bay.',
    price: 120000,
    deposit: 240000,
    maintenance: 5000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Bandra West',
    address: 'Linking Road, Bandra West, Mumbai',
    latitude: 19.0621,
    longitude: 72.8347,
    bedrooms: null,
    bathrooms: 1,
    area: 850,
    furnishing: 'unfurnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['parking', 'power_backup', 'security'],
    tenant_preferences: ['working_professionals'],
    views_count: 710,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '600m to Metro',
    aiWhyRecommended: 'High Footfall Street • Glass Facade • Corner Unit',
    aiMatchScore: 95,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-12-1',
        image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-12-2',
        image_url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  // =========================================================================
  // DEDICATED VERIFIED MUMBAI PG & STUDENT HOSTELS (VERIFIED LISTING)
  // =========================================================================
  {
    id: 'prop-pg-01',
    title: 'Zolo-Style Premium Boys PG & Co-Living Space',
    category: 'residential',
    type: 'pg',
    description: 'Fully furnished AC twin-sharing & private rooms with 3 daily North & South Indian meals, high-speed optical WiFi, daily housekeeping, and gaming lounge.',
    price: 14500,
    deposit: 14500,
    maintenance: 0,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Andheri West',
    address: 'Near Infinity Mall, Link Road, Andheri West, Mumbai',
    latitude: 19.1363,
    longitude: 72.8277,
    bedrooms: '1',
    bathrooms: 1,
    area: 280,
    furnishing: 'fully_furnished',
    parking: 'Bike Only',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['wifi', 'ac', 'food', 'laundry', 'security', 'power_backup', 'lift'],
    tenant_preferences: ['bachelors', 'students', 'working_professionals'],
    views_count: 1420,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '250m to DN Nagar Metro',
    aiWhyRecommended: 'Meals Included • Optical WiFi • Verified Listing',
    aiMatchScore: 99,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-pg-1-1',
        image_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-pg-1-2',
        image_url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-pg-02',
    title: 'Luxury Girls PG & Student Hostel near NMIMS & Mithibai',
    category: 'residential',
    type: 'pg',
    description: 'Safe girls hostel with biometric entry, 24x7 female warden, nutritious home-cooked meals, study desks, and attached bathrooms.',
    price: 18500,
    deposit: 18500,
    maintenance: 0,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Vile Parle West',
    address: 'Gulmohar Road, Near NMIMS, Vile Parle West, Mumbai',
    latitude: 19.1030,
    longitude: 72.8360,
    bedrooms: '1',
    bathrooms: 1,
    area: 320,
    furnishing: 'fully_furnished',
    parking: 'None',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['wifi', 'ac', 'food', 'laundry', 'security', 'cctv', 'lift'],
    tenant_preferences: ['female_only', 'students'],
    views_count: 1890,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '400m to Vile Parle Station',
    aiWhyRecommended: 'Female Warden • 3 Daily Meals • Walking to Colleges',
    aiMatchScore: 98,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-pg-2-1',
        image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-pg-2-2',
        image_url: 'https://images.unsplash.com/photo-1540518614846-7ede433c4550?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-pg-03',
    title: 'Tech Co-Living & Student Hostel near IIT Bombay',
    category: 'residential',
    type: 'pg',
    description: 'Modern co-living space for engineering students and tech interns. 300 Mbps high-speed WiFi, dedicated workstation, buffet meals, and gym access.',
    price: 13000,
    deposit: 13000,
    maintenance: 0,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Powai',
    address: 'Near IIT Main Gate, Powai, Mumbai',
    latitude: 19.1250,
    longitude: 72.9100,
    bedrooms: '1',
    bathrooms: 1,
    area: 250,
    furnishing: 'fully_furnished',
    parking: 'Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['wifi', 'ac', 'food', 'power_backup', 'security', 'gym'],
    tenant_preferences: ['students', 'working_professionals'],
    views_count: 1120,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '500m to Powai Metro',
    aiWhyRecommended: 'Next to IIT Bombay • 300 Mbps WiFi • Buffet Meals',
    aiMatchScore: 97,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-pg-3-1',
        image_url: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  {
    id: 'prop-pg-04',
    title: 'Boutique Sea-Breeze Executive Co-Living PG in Bandra',
    category: 'residential',
    type: 'pg',
    description: 'Premium co-living space for corporate professionals. Private air-conditioned studio room, rooftop terrace, barista coffee machine, and verified marketplace.',
    price: 24000,
    deposit: 0,
    maintenance: 0,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Bandra West',
    address: 'Pali Hill, Bandra West, Mumbai',
    latitude: 19.0645,
    longitude: 72.8290,
    bedrooms: '1',
    bathrooms: 1,
    area: 360,
    furnishing: 'fully_furnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['wifi', 'ac', 'food', 'security', 'lift', 'power_backup'],
    tenant_preferences: ['working_professionals'],
    views_count: 1650,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '650m to Bandra Station',
    aiWhyRecommended: 'Zero Deposit • Sea Breeze • Executive Lifestyle',
    aiMatchScore: 99,
    isZeroDeposit: true,
    property_images: [
      {
        id: 'img-pg-4-1',
        image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  {
    id: 'prop-pg-05',
    title: 'Comfort Boys PG & Hostel near BKC Financial Hub',
    category: 'residential',
    type: 'pg',
    description: 'Affordable clean twin-sharing rooms with meal plan, daily housekeeping, RO drinking water, and quick 5-min access to BKC offices.',
    price: 11500,
    deposit: 11500,
    maintenance: 0,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'BKC',
    address: 'Near Bharat Diamond Bourse, BKC, Mumbai',
    latitude: 19.0680,
    longitude: 72.8680,
    bedrooms: '1',
    bathrooms: 1,
    area: 240,
    furnishing: 'fully_furnished',
    parking: 'Bike Only',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['wifi', 'ac', 'food', 'laundry', 'security'],
    tenant_preferences: ['bachelors', 'working_professionals'],
    views_count: 980,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '300m to BKC Metro',
    aiWhyRecommended: 'Walking Distance to BKC • 3 Meals • Low Rent',
    aiMatchScore: 96,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-pg-5-1',
        image_url: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  // =========================================================================
  // DEDICATED VERIFIED MUMBAI COMMERCIAL & OFFICES (VERIFIED LISTING)
  // =========================================================================
  {
    id: 'prop-comm-01',
    title: 'Plug-and-Play Corporate Office Floor in Grade-A Tower',
    category: 'commercial',
    type: 'office',
    description: 'Ready-to-move corporate office with 36 workstations, 3 executive director cabins, 12-seater boardroom, cafeteria, and 2 reserved car parkings.',
    price: 260000,
    deposit: 520000,
    maintenance: 18000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'BKC',
    address: 'G Block, Bandra Kurla Complex, Mumbai',
    latitude: 19.0650,
    longitude: 72.8690,
    bedrooms: null,
    bathrooms: 4,
    area: 2400,
    furnishing: 'fully_furnished',
    parking: '2 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['power_backup', 'lift', 'parking', 'security', 'cctv'],
    tenant_preferences: ['working_professionals'],
    views_count: 2240,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '200m to BKC Metro Line 3',
    aiWhyRecommended: 'Grade-A Tower • 36 Workstations • Verified Listing',
    aiMatchScore: 99,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-comm-1-1',
        image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
      {
        id: 'img-comm-1-2',
        image_url: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1000&auto=format&fit=crop&q=80',
        is_cover: false,
        sort_order: 2,
      },
    ],
  },
  {
    id: 'prop-comm-02',
    title: 'Modern Tech Workspace & Creative Studio in MIDC',
    category: 'commercial',
    type: 'office',
    description: 'Fully furnished tech workspace 2 mins from Chakala Metro. 24 workstations, meeting room, sound-treated podcast/video booth, and 100% DG backup.',
    price: 155000,
    deposit: 310000,
    maintenance: 12000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Andheri East',
    address: 'MIDC Central Road, Andheri East, Mumbai',
    latitude: 19.1190,
    longitude: 72.8680,
    bedrooms: null,
    bathrooms: 2,
    area: 1650,
    furnishing: 'fully_furnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['power_backup', 'lift', 'parking', 'security'],
    tenant_preferences: ['working_professionals'],
    views_count: 1480,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '150m to Chakala Metro',
    aiWhyRecommended: 'Plug & Play • 24 Desks • Metro Adjacent',
    aiMatchScore: 97,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-comm-2-1',
        image_url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  {
    id: 'prop-comm-03',
    title: 'Prime Retail Commercial Showroom with 24ft Glass Frontage',
    category: 'commercial',
    type: 'showroom',
    description: 'Direct owner ground-floor commercial showroom facing high-footfall main avenue. 18-foot clear ceiling height, 3-phase commercial power, ideal for luxury brand.',
    price: 320000,
    deposit: 640000,
    maintenance: 15000,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Lower Parel',
    address: 'Senapati Bapat Marg, Lower Parel, Mumbai',
    latitude: 19.0010,
    longitude: 72.8290,
    bedrooms: null,
    bathrooms: 2,
    area: 2600,
    furnishing: 'semi_furnished',
    parking: '2 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['power_backup', 'parking', 'security', 'lift'],
    tenant_preferences: ['working_professionals'],
    views_count: 2890,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '400m to Lower Parel Monorail',
    aiWhyRecommended: '18ft Ceiling • 24ft Glass Frontage • High Footfall',
    aiMatchScore: 98,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-comm-3-1',
        image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
  {
    id: 'prop-comm-04',
    title: 'Managed Coworking Team Suite & Flex Workspaces',
    category: 'commercial',
    type: 'coworking',
    description: 'Private 12-seater managed team office suite inside premium Hiranandani complex. Includes high-speed leased line internet, meeting room credits, and reception.',
    price: 68000,
    deposit: 68000,
    maintenance: 0,
    brokerage: 0,
    city: 'Mumbai',
    state: 'Maharashtra',
    locality: 'Powai',
    address: 'Hiranandani Business Park, Powai, Mumbai',
    latitude: 19.1180,
    longitude: 72.9080,
    bedrooms: null,
    bathrooms: 2,
    area: 880,
    furnishing: 'fully_furnished',
    parking: '1 Covered',
    availability: 'Immediate',
    status: 'published',
    verification_status: 'verified',
    amenities: ['wifi', 'power_backup', 'lift', 'security', 'parking'],
    tenant_preferences: ['working_professionals'],
    views_count: 1750,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    metroDistance: '500m to Powai Metro',
    aiWhyRecommended: 'All Inclusive • 12 Workstations • Meeting Credits',
    aiMatchScore: 96,
    isZeroDeposit: false,
    property_images: [
      {
        id: 'img-comm-4-1',
        image_url: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=1000&auto=format&fit=crop&q=80',
        is_cover: true,
        sort_order: 1,
      },
    ],
  },
];
