import { AdminUser, AdminRole } from '@/types/admin';
import { PermissionModule, RolePermissionConfig } from '@/types/rbac';

export type { AdminRole, AdminUser } from '@/types/admin';
export { ADMIN_ROLES } from '@/types/admin';

export const MOCK_ADMIN_USERS: Record<AdminRole, AdminUser> = {
  SUPER_ADMIN: {
    id: 'admin_usr_01',
    user_id: 'usr_super_admin',
    employee_id: 'RHV-001',
    email: 'admin@rehvo.com',
    full_name: 'Antigravity Super Admin',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    department: 'Leadership & Executive',
    city: 'Mumbai',
    phone: '+91 98200 11223',
    joining_date: '2024-01-15',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  ADMIN: {
    id: 'admin_usr_02',
    user_id: 'usr_admin',
    employee_id: 'RHV-002',
    email: 'operations.lead@rehvo.com',
    full_name: 'Priya Deshmukh',
    role: 'ADMIN',
    status: 'ACTIVE',
    department: 'General Administration',
    city: 'Mumbai',
    phone: '+91 98201 22334',
    joining_date: '2024-02-01',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  PROPERTY_MODERATOR: {
    id: 'admin_usr_03',
    user_id: 'usr_prop_mod',
    employee_id: 'RHV-003',
    email: 'moderator@rehvo.com',
    full_name: 'Rohit Kulkarni',
    role: 'PROPERTY_MODERATOR',
    status: 'ACTIVE',
    department: 'Listing Moderation & Quality',
    city: 'Mumbai',
    phone: '+91 98202 33445',
    joining_date: '2024-03-10',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-03-10T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  SUPPORT_EXECUTIVE: {
    id: 'admin_usr_04',
    user_id: 'usr_support',
    employee_id: 'RHV-004',
    email: 'support.lead@rehvo.com',
    full_name: 'Ananya Sharma',
    role: 'SUPPORT_EXECUTIVE',
    status: 'ACTIVE',
    department: 'Tenant & Owner Success',
    city: 'Mumbai',
    phone: '+91 98203 44556',
    joining_date: '2024-04-05',
    is_online: true,
    assigned_tickets_count: 7,
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-04-05T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  FINANCE_MANAGER: {
    id: 'admin_usr_05',
    user_id: 'usr_finance',
    employee_id: 'RHV-005',
    email: 'finance@rehvo.com',
    full_name: 'Karan Mehta',
    role: 'FINANCE_MANAGER',
    status: 'ACTIVE',
    department: 'Finance & Treasury',
    city: 'Mumbai',
    phone: '+91 98204 55667',
    joining_date: '2024-02-20',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-02-20T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  SALES_EXECUTIVE: {
    id: 'admin_usr_06',
    user_id: 'usr_sales',
    employee_id: 'RHV-006',
    email: 'sales@rehvo.com',
    full_name: 'Vikram Singh',
    role: 'SALES_EXECUTIVE',
    status: 'ACTIVE',
    department: 'Owner Onboarding & Commercial',
    city: 'Mumbai',
    phone: '+91 98205 66778',
    joining_date: '2024-05-12',
    is_online: false,
    assigned_visits_count: 12,
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-05-12T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  CONTENT_MANAGER: {
    id: 'admin_usr_07',
    user_id: 'usr_content',
    employee_id: 'RHV-007',
    email: 'content@rehvo.com',
    full_name: 'Nisha Verma',
    role: 'CONTENT_MANAGER',
    status: 'ACTIVE',
    department: 'Media & CMS Operations',
    city: 'Mumbai',
    phone: '+91 98206 77889',
    joining_date: '2024-03-25',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-03-25T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  MARKETING_MANAGER: {
    id: 'admin_usr_08',
    user_id: 'usr_marketing',
    employee_id: 'RHV-008',
    email: 'growth@rehvo.com',
    full_name: 'Aditya Roy',
    role: 'MARKETING_MANAGER',
    status: 'ACTIVE',
    department: 'Growth & Campaigns',
    city: 'Mumbai',
    phone: '+91 98207 88990',
    joining_date: '2024-04-18',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-04-18T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  AI_MANAGER: {
    id: 'admin_usr_09',
    user_id: 'usr_ai',
    employee_id: 'RHV-009',
    email: 'ai.concierge@rehvo.com',
    full_name: 'Devika Nair',
    role: 'AI_MANAGER',
    status: 'ACTIVE',
    department: 'AI Systems & Prompts',
    city: 'Mumbai',
    phone: '+91 98208 99001',
    joining_date: '2024-01-20',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-01-20T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
  OPERATIONS_MANAGER: {
    id: 'admin_usr_10',
    user_id: 'usr_ops',
    employee_id: 'RHV-010',
    email: 'operations@rehvo.com',
    full_name: 'Sameer Joshi',
    role: 'OPERATIONS_MANAGER',
    status: 'ACTIVE',
    department: 'City Operations & Field',
    city: 'Mumbai',
    phone: '+91 98209 00112',
    joining_date: '2024-02-15',
    is_online: true,
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&auto=format&fit=crop&q=80',
    created_at: '2024-02-15T10:00:00Z',
    updated_at: new Date().toISOString(),
  },
};

export const MOCK_ADMIN_USER: AdminUser = MOCK_ADMIN_USERS.SUPER_ADMIN;

export const ADMIN_ROLE_LABELS: Record<AdminRole, string> = {
  SUPER_ADMIN: 'Super Admin',
  ADMIN: 'Admin',
  PROPERTY_MODERATOR: 'Property Moderator',
  SUPPORT_EXECUTIVE: 'Support Executive',
  FINANCE_MANAGER: 'Finance Manager',
  SALES_EXECUTIVE: 'Sales Executive',
  CONTENT_MANAGER: 'Content Manager',
  MARKETING_MANAGER: 'Marketing Manager',
  AI_MANAGER: 'AI Manager',
  OPERATIONS_MANAGER: 'Operations Manager',
};

export const ADMIN_ROLE_COLORS: Record<AdminRole, { bg: string; text: string; border: string }> = {
  SUPER_ADMIN: { bg: 'rgba(14, 143, 115, 0.15)', text: '#10B981', border: 'rgba(14, 143, 115, 0.4)' },
  ADMIN: { bg: 'rgba(59, 130, 246, 0.15)', text: '#60A5FA', border: 'rgba(59, 130, 246, 0.4)' },
  PROPERTY_MODERATOR: { bg: 'rgba(245, 158, 11, 0.15)', text: '#FBBF24', border: 'rgba(245, 158, 11, 0.4)' },
  SUPPORT_EXECUTIVE: { bg: 'rgba(168, 85, 247, 0.15)', text: '#C084FC', border: 'rgba(168, 85, 247, 0.4)' },
  FINANCE_MANAGER: { bg: 'rgba(239, 68, 68, 0.15)', text: '#F87171', border: 'rgba(239, 68, 68, 0.4)' },
  SALES_EXECUTIVE: { bg: 'rgba(20, 184, 166, 0.15)', text: '#2DD4BF', border: 'rgba(20, 184, 166, 0.4)' },
  CONTENT_MANAGER: { bg: 'rgba(236, 72, 153, 0.15)', text: '#F472B6', border: 'rgba(236, 72, 153, 0.4)' },
  MARKETING_MANAGER: { bg: 'rgba(139, 92, 246, 0.15)', text: '#A78BFA', border: 'rgba(139, 92, 246, 0.4)' },
  AI_MANAGER: { bg: 'rgba(6, 182, 212, 0.15)', text: '#22D3EE', border: 'rgba(6, 182, 212, 0.4)' },
  OPERATIONS_MANAGER: { bg: 'rgba(99, 102, 241, 0.15)', text: '#818CF8', border: 'rgba(99, 102, 241, 0.4)' },
};

/**
 * Default granular permissions by Role
 */
export const ROLE_DEFAULT_PERMISSIONS: Record<AdminRole, RolePermissionConfig> = {
  SUPER_ADMIN: {
    dashboard: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    properties: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    property_edit: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    property_approval: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    property_delete: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    users: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    owners: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    flatmates: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    pg_hostels: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    commercial: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    society: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    payments: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    refunds: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    kyc: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    chats: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    visits: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    showreels: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    cms: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    notifications: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    ai: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    support: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    analytics: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    staff: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    security: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    settings: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
  },
  ADMIN: {
    dashboard: { view: true, export: true },
    properties: { view: true, edit: true, approve: true, export: true },
    property_edit: { view: true, edit: true },
    property_approval: { view: true, approve: true },
    property_delete: { view: true, delete: false },
    users: { view: true, edit: true, export: true },
    owners: { view: true, edit: true, export: true },
    flatmates: { view: true, edit: true, approve: true },
    pg_hostels: { view: true, edit: true },
    commercial: { view: true, edit: true },
    society: { view: true, edit: true },
    payments: { view: true, export: true },
    refunds: { view: true, approve: false },
    kyc: { view: true, approve: true },
    chats: { view: true },
    visits: { view: true, edit: true },
    showreels: { view: true, edit: true },
    cms: { view: true, edit: true },
    notifications: { view: true, create: true },
    ai: { view: true },
    support: { view: true, edit: true },
    analytics: { view: true, export: true },
    staff: { view: true },
    security: { view: false },
    settings: { view: true, edit: true },
  },
  PROPERTY_MODERATOR: {
    dashboard: { view: true },
    properties: { view: true, edit: true, approve: true },
    property_edit: { view: true, edit: true },
    property_approval: { view: true, approve: true },
    property_delete: { view: false },
    users: { view: false },
    owners: { view: true },
    flatmates: { view: true, approve: true },
    pg_hostels: { view: true, edit: true },
    commercial: { view: true, edit: true },
    society: { view: false },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: true, approve: true },
    chats: { view: false },
    visits: { view: true },
    showreels: { view: true },
    cms: { view: false },
    notifications: { view: false },
    ai: { view: false },
    support: { view: false },
    analytics: { view: false },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  SUPPORT_EXECUTIVE: {
    dashboard: { view: true },
    properties: { view: true },
    property_edit: { view: false },
    property_approval: { view: false },
    property_delete: { view: false },
    users: { view: true },
    owners: { view: true },
    flatmates: { view: true },
    pg_hostels: { view: true },
    commercial: { view: true },
    society: { view: false },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: false },
    chats: { view: true, edit: true },
    visits: { view: true, edit: true },
    showreels: { view: false },
    cms: { view: false },
    notifications: { view: false },
    ai: { view: false },
    support: { view: true, edit: true, create: true },
    analytics: { view: false },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  FINANCE_MANAGER: {
    dashboard: { view: true, export: true },
    properties: { view: false },
    property_edit: { view: false },
    property_approval: { view: false },
    property_delete: { view: false },
    users: { view: true },
    owners: { view: true },
    flatmates: { view: false },
    pg_hostels: { view: false },
    commercial: { view: false },
    society: { view: false },
    payments: { view: true, edit: true, export: true },
    refunds: { view: true, approve: true, export: true },
    kyc: { view: false },
    chats: { view: false },
    visits: { view: false },
    showreels: { view: false },
    cms: { view: false },
    notifications: { view: false },
    ai: { view: false },
    support: { view: false },
    analytics: { view: true, export: true },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  SALES_EXECUTIVE: {
    dashboard: { view: true },
    properties: { view: true, create: true },
    property_edit: { view: true, edit: true },
    property_approval: { view: false },
    property_delete: { view: false },
    users: { view: true },
    owners: { view: true, create: true, edit: true },
    flatmates: { view: false },
    pg_hostels: { view: true },
    commercial: { view: true },
    society: { view: true },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: false },
    chats: { view: true },
    visits: { view: true, edit: true, create: true },
    showreels: { view: false },
    cms: { view: false },
    notifications: { view: false },
    ai: { view: false },
    support: { view: false },
    analytics: { view: false },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  CONTENT_MANAGER: {
    dashboard: { view: true },
    properties: { view: true },
    property_edit: { view: false },
    property_approval: { view: false },
    property_delete: { view: false },
    users: { view: false },
    owners: { view: false },
    flatmates: { view: false },
    pg_hostels: { view: false },
    commercial: { view: false },
    society: { view: false },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: false },
    chats: { view: false },
    visits: { view: false },
    showreels: { view: true, create: true, edit: true, delete: true },
    cms: { view: true, create: true, edit: true, approve: true },
    notifications: { view: false },
    ai: { view: false },
    support: { view: false },
    analytics: { view: true },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  MARKETING_MANAGER: {
    dashboard: { view: true, export: true },
    properties: { view: true },
    property_edit: { view: false },
    property_approval: { view: false },
    property_delete: { view: false },
    users: { view: true, export: true },
    owners: { view: true },
    flatmates: { view: true },
    pg_hostels: { view: false },
    commercial: { view: false },
    society: { view: false },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: false },
    chats: { view: false },
    visits: { view: false },
    showreels: { view: true },
    cms: { view: true, edit: true },
    notifications: { view: true, create: true, edit: true, approve: true, export: true },
    ai: { view: false },
    support: { view: false },
    analytics: { view: true, export: true },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  AI_MANAGER: {
    dashboard: { view: true },
    properties: { view: true },
    property_edit: { view: false },
    property_approval: { view: false },
    property_delete: { view: false },
    users: { view: false },
    owners: { view: false },
    flatmates: { view: false },
    pg_hostels: { view: false },
    commercial: { view: false },
    society: { view: false },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: false },
    chats: { view: true },
    visits: { view: false },
    showreels: { view: false },
    cms: { view: false },
    notifications: { view: false },
    ai: { view: true, create: true, edit: true, approve: true, delete: true, export: true },
    support: { view: false },
    analytics: { view: true },
    staff: { view: false },
    security: { view: false },
    settings: { view: false },
  },
  OPERATIONS_MANAGER: {
    dashboard: { view: true, export: true },
    properties: { view: true, edit: true, approve: true, export: true },
    property_edit: { view: true, edit: true },
    property_approval: { view: true, approve: true },
    property_delete: { view: false },
    users: { view: true, edit: true, export: true },
    owners: { view: true, edit: true, export: true },
    flatmates: { view: true, edit: true, approve: true },
    pg_hostels: { view: true, edit: true },
    commercial: { view: true, edit: true },
    society: { view: true, edit: true },
    payments: { view: false },
    refunds: { view: false },
    kyc: { view: true, approve: true },
    chats: { view: true },
    visits: { view: true, edit: true, approve: true },
    showreels: { view: true },
    cms: { view: false },
    notifications: { view: true, create: true },
    ai: { view: false },
    support: { view: true, edit: true },
    analytics: { view: true, export: true },
    staff: { view: true, edit: true },
    security: { view: false },
    settings: { view: true },
  },
};

/**
 * Check if the active role has view permission for a specific module
 */
export function canViewModule(role: AdminRole, moduleName: PermissionModule): boolean {
  if (role === 'SUPER_ADMIN') return true;
  const permissions = ROLE_DEFAULT_PERMISSIONS[role];
  return permissions ? !!permissions[moduleName]?.view : false;
}

/**
 * Storage helpers for dynamic role switching in development
 */
export function getActiveAdminRole(): AdminRole {
  if (typeof window !== 'undefined') {
    const saved = localStorage.getItem('rehvo_admin_active_role');
    if (saved && Object.keys(MOCK_ADMIN_USERS).includes(saved)) {
      return saved as AdminRole;
    }
  }
  return 'SUPER_ADMIN';
}

export function setActiveAdminRole(role: AdminRole): void {
  if (typeof window !== 'undefined') {
    localStorage.setItem('rehvo_admin_active_role', role);
    window.dispatchEvent(new CustomEvent('rehvo-admin-role-change', { detail: { role } }));
  }
}

export function getActiveAdminUser(): AdminUser {
  const role = getActiveAdminRole();
  return MOCK_ADMIN_USERS[role] || MOCK_ADMIN_USERS.SUPER_ADMIN;
}
