export const REHVO_COLORS = {
  primaryInk: '#17151F',
  warmIvory: '#F7F5F0',
  signatureViolet: '#6C4DFF',
  softViolet: '#EEE9FF',
  coral: '#FF6B4A',
  softCoral: '#FFF0EB',
  successGreen: '#32B768',
  softGreen: '#EAF8F0',
  pureWhite: '#FFFFFF',
  surfaceVariant: '#E4E2DD',
  outlineVariant: '#C9C5CC',
  outline: '#79767C',
  surfaceContainerLow: '#F5F3EE',
  surfaceContainerHigh: '#EAE8E3',
  onSurfaceVariant: '#48464B',
  darkContainer: '#1C1A24',
};

export const MUMBAI_LOCALITIES = [
  'Andheri West',
  'Andheri East',
  'Bandra West',
  'Bandra East',
  'Powai',
  'Juhu',
  'Lokhandwala',
  'Lower Parel',
  'Worli',
  'Colaba',
  'Ghatkopar West',
  'Malad West',
  'Goregaon West',
  'Thane West',
  'Navi Mumbai - Vashi',
  'Khar West',
  'Santacruz West',
];

export const AMENITIES_LIST = [
  'Wi-Fi',
  'AC',
  'Parking',
  'Lift',
  'Balcony',
  'Washing Machine',
  'Kitchen',
  'TV',
  'Power Backup',
  'Security 24/7',
  'Gym',
  'Swimming Pool',
  'Housekeeping',
  'Food Provided',
  'CCTV',
  'RO Water',
];

export const TENANT_PREFERENCES_LIST = [
  'Bachelors Allowed',
  'Working Professionals Preferred',
  'Students Allowed',
  'Family Preferred',
  'Vegetarian Preferred',
  'Non-Smoker Preferred',
  'Pets Allowed',
];
