#!/usr/bin/env python3
"""
REHVO Property Payload & Schema Contract Assertion Script
Validates that:
1. Canonical database columns in 002_properties.sql are parsed.
2. The property insertion payload generated by mapListingFormToPropertyInsert contains ONLY valid DB columns.
3. The property update payload generated by mapListingFormToPropertyUpdate contains ONLY valid DB columns.
4. No unsupported UI fields (e.g. carpet_area, business_type, floor_number, washrooms) can be sent to Supabase.
"""

import os
import sys
import re

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SCHEMA_SQL = os.path.join(ROOT_DIR, 'supabase', 'migrations', '002_properties.sql')
WEB_SERVICE = os.path.join(ROOT_DIR, 'web', 'src', 'services', 'properties.ts')

CANONICAL_DB_COLUMNS = {
    'id',
    'owner_id',
    'type',
    'title',
    'description',
    'price',
    'deposit',
    'maintenance',
    'brokerage',
    'city',
    'state',
    'locality',
    'address',
    'latitude',
    'longitude',
    'bedrooms',
    'bathrooms',
    'area',
    'furnishing',
    'parking',
    'availability',
    'status',
    'verification_status',
    'amenities',
    'tenant_preferences',
    'views_count',
    'saves_count',
    'enquiries_count',
    'created_at',
    'updated_at',
}

FORBIDDEN_COLUMNS = {
    'carpet_area',
    'business_type',
    'floor_number',
    'total_floors',
    'washrooms',
    'parking_spaces',
    'power_backup',
    'lift',
    'possession_status',
    'lease_type',
    'road_width',
    'commercial_type',
    'built_up_area',
    'super_built_up_area',
    'area_sqft',
}

def verify_web_service_payload_contract():
    print("\n--- Auditing web/src/services/properties.ts Payload Contract ---")
    if not os.path.exists(WEB_SERVICE):
        print(f"❌ FAIL: web service not found at {WEB_SERVICE}")
        return False

    with open(WEB_SERVICE, 'r', encoding='utf-8') as f:
        code = f.read()

    # Extract keys inside mapListingFormToPropertyInsert return object
    insert_match = re.search(r'return\s*\{([^}]+status:\s*status[^}]+)\};', code, re.DOTALL)
    if not insert_match:
        print("❌ FAIL: Could not find return object in mapListingFormToPropertyInsert")
        return False

    return_body = insert_match.group(1)
    # Extract keys
    keys = re.findall(r'([a-zA-Z0-9_]+)\s*:', return_body)
    
    print(f"Found {len(keys)} mapped keys in insert payload: {keys}")

    # Check that each key is a valid DB column
    for key in keys:
        if key in FORBIDDEN_COLUMNS:
            print(f"❌ FAIL: Forbidden UI field '{key}' found in insert payload!")
            return False
        if key not in CANONICAL_DB_COLUMNS:
            print(f"❌ FAIL: Key '{key}' is NOT in canonical DB columns (002_properties.sql)")
            return False

    print("✅ PASS: All insert payload keys strictly match canonical DB columns")

    # Check update mapper keys
    update_keys = re.findall(r'payload\.([a-zA-Z0-9_]+)\s*=', code)
    print(f"Found {len(update_keys)} mapped keys in update payload: {set(update_keys)}")

    for key in set(update_keys):
        if key in FORBIDDEN_COLUMNS:
            print(f"❌ FAIL: Forbidden UI field '{key}' found in update payload!")
            return False
        if key not in CANONICAL_DB_COLUMNS and key != 'updated_at':
            print(f"❌ FAIL: Key '{key}' is NOT in canonical DB columns")
            return False

    print("✅ PASS: All update payload keys strictly match canonical DB columns")
    return True

def main():
    print("=" * 60)
    print("REHVO PROPERTY PAYLOAD & DATABASE CONTRACT AUDIT")
    print("=" * 60)

    contract_ok = verify_web_service_payload_contract()
    if not contract_ok:
        print("\n❌ Contract check failed!")
        sys.exit(1)

    print("\n🎉 ALL PROPERTY PAYLOAD CONTRACT CHECKS PASSED!")

if __name__ == '__main__':
    main()
