import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET() {
  const topPages = [
    {
      url: 'https://rehvo.in/',
      path: '/',
      pageTitle: 'REHVO — Zero Brokerage Rentals, Verified Homes & Flatmates in Mumbai',
      clicks: 4280,
      impressions: 54100,
      ctr: 7.91,
      position: 2.4,
      category: 'Core',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/mumbai/bandra-west',
      path: '/mumbai/bandra-west',
      pageTitle: 'Flats, Rooms & Flatmates for Rent in Bandra West, Mumbai | REHVO',
      clicks: 2940,
      impressions: 38200,
      ctr: 7.70,
      position: 3.1,
      category: 'Locality',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/mumbai/andheri-west',
      path: '/mumbai/andheri-west',
      pageTitle: 'Flats, Rooms & Flatmates for Rent in Andheri West, Mumbai | REHVO',
      clicks: 2610,
      impressions: 34900,
      ctr: 7.48,
      position: 3.4,
      category: 'Locality',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/mumbai/powai',
      path: '/mumbai/powai',
      pageTitle: 'Flats, Rooms & Flatmates for Rent in Powai, Mumbai | REHVO',
      clicks: 2150,
      impressions: 28400,
      ctr: 7.57,
      position: 3.8,
      category: 'Locality',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/rent/flats-near-iit-bombay',
      path: '/rent/flats-near-iit-bombay',
      pageTitle: 'Flats for Rent near IIT Bombay Powai | Verified Direct Owners | Zero Brokerage',
      clicks: 1890,
      impressions: 21600,
      ctr: 8.75,
      position: 2.1,
      category: 'Landing',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/rent/flats-near-bkc',
      path: '/rent/flats-near-bkc',
      pageTitle: 'Flats for Rent near BKC Bandra Kurla Complex | Zero Brokerage | REHVO',
      clicks: 1740,
      impressions: 23100,
      ctr: 7.53,
      position: 3.2,
      category: 'Landing',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/rent/1-bhk-for-rent-in-mumbai',
      path: '/rent/1-bhk-for-rent-in-mumbai',
      pageTitle: '1 BHK Flats for Rent in Mumbai | Verified Direct Owners | Zero Brokerage',
      clicks: 1650,
      impressions: 29800,
      ctr: 5.54,
      position: 4.6,
      category: 'Landing',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/rent/2-bhk-for-rent-in-mumbai',
      path: '/rent/2-bhk-for-rent-in-mumbai',
      pageTitle: '2 BHK Flats for Rent in Mumbai | Verified Direct Owners | Zero Brokerage',
      clicks: 1580,
      impressions: 31200,
      ctr: 5.06,
      position: 4.8,
      category: 'Landing',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/mumbai/worli',
      path: '/mumbai/worli',
      pageTitle: 'Flats, Rooms & Flatmates for Rent in Worli, Mumbai | REHVO',
      clicks: 1420,
      impressions: 19500,
      ctr: 7.28,
      position: 3.9,
      category: 'Locality',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/flatmates',
      path: '/flatmates',
      pageTitle: 'Find Verified Flatmates in Mumbai | AI Lifestyle Match | Zero Brokerage | REHVO',
      clicks: 1390,
      impressions: 17400,
      ctr: 7.99,
      position: 2.8,
      category: 'Core',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/rent/studio-apartments-in-mumbai',
      path: '/rent/studio-apartments-in-mumbai',
      pageTitle: 'Studio Apartments for Rent in Mumbai | 1 RK Verified Flats | Zero Brokerage',
      clicks: 1240,
      impressions: 16200,
      ctr: 7.65,
      position: 3.5,
      category: 'Landing',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/blog/complete-tenant-guide-renting-mumbai-2026',
      path: '/blog/complete-tenant-guide-renting-mumbai-2026',
      pageTitle: 'Complete Guide to Renting a Flat in Mumbai (2026 Edition) | REHVO Blog',
      clicks: 1120,
      impressions: 14800,
      ctr: 7.57,
      position: 3.0,
      category: 'Editorial',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/pg',
      path: '/pg',
      pageTitle: 'Best PG & Hostels in Mumbai | Verified Paying Guest Rentals | REHVO',
      clicks: 980,
      impressions: 15400,
      ctr: 6.36,
      position: 4.9,
      category: 'Core',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/commercial',
      path: '/commercial',
      pageTitle: 'Commercial Offices & Retail Shops for Rent in Mumbai | Zero Brokerage | REHVO',
      clicks: 890,
      impressions: 12900,
      ctr: 6.90,
      position: 4.1,
      category: 'Core',
      status: 'Indexed',
    },
    {
      url: 'https://rehvo.in/reports/mumbai-rental-yield-index-2026',
      path: '/reports/mumbai-rental-yield-index-2026',
      pageTitle: 'Mumbai Rental Yield & Micro-Market Price Index 2026 | REHVO Intelligence',
      clicks: 810,
      impressions: 9400,
      ctr: 8.62,
      position: 2.2,
      category: 'Report',
      status: 'Indexed',
    },
  ];

  return NextResponse.json({
    pages: topPages,
    totalCount: topPages.length,
    generatedAt: new Date().toISOString(),
  });
}
